In [1]:
import numpy as np
import pandas as pd

In [2]:
seq_list = [[[np.random.randint(0,100) for _ in range(np.random.randint(398, 401))] for _ in range(80)] for _ in range(1000)]

In [3]:
len(seq_list)

1000

In [4]:
Y=np.random.randint(0, 2,1000)
Y=np.reshape(Y, (1000, 1))

In [5]:
from keras.preprocessing.sequence import pad_sequences
X=[]
for i in range(1000):
  padded = pad_sequences(seq_list[i])
  X.append(padded)
print(X)

[array([[ 0,  0, 36, ..., 77, 79, 58],
       [91,  0, 99, ..., 44,  5, 17],
       [ 0, 94, 86, ..., 89, 39, 89],
       ...,
       [ 0, 45, 46, ..., 18, 87, 46],
       [95, 33, 43, ..., 66, 73, 68],
       [ 0,  0,  8, ..., 67, 50, 17]], dtype=int32), array([[ 0, 90, 15, ..., 93, 73, 80],
       [ 0, 14, 32, ..., 12, 26, 78],
       [ 0, 24, 11, ..., 73, 95, 65],
       ...,
       [ 0, 30, 11, ..., 75,  3, 94],
       [31, 61, 96, ..., 34, 75, 97],
       [ 0, 36, 60, ..., 73, 52, 24]], dtype=int32), array([[47, 72, 76, ..., 88, 87, 91],
       [36, 95, 42, ..., 70,  8, 17],
       [72, 68, 33, ..., 86, 53, 14],
       ...,
       [ 0, 12, 95, ..., 74,  9, 25],
       [23,  0, 27, ..., 72, 98, 78],
       [ 0,  0, 74, ..., 58, 40, 60]], dtype=int32), array([[ 0,  0, 12, ...,  9, 53, 69],
       [ 0, 14, 66, ..., 98,  6, 33],
       [ 0, 19, 28, ..., 39, 37, 73],
       ...,
       [71, 60, 86, ..., 77, 20, 26],
       [72, 26,  1, ..., 77, 88, 99],
       [ 0, 95,  8, ..., 97, 52,

In [6]:
X= np.array(X)

In [7]:
X

array([[[ 0,  0, 36, ..., 77, 79, 58],
        [91,  0, 99, ..., 44,  5, 17],
        [ 0, 94, 86, ..., 89, 39, 89],
        ...,
        [ 0, 45, 46, ..., 18, 87, 46],
        [95, 33, 43, ..., 66, 73, 68],
        [ 0,  0,  8, ..., 67, 50, 17]],

       [[ 0, 90, 15, ..., 93, 73, 80],
        [ 0, 14, 32, ..., 12, 26, 78],
        [ 0, 24, 11, ..., 73, 95, 65],
        ...,
        [ 0, 30, 11, ..., 75,  3, 94],
        [31, 61, 96, ..., 34, 75, 97],
        [ 0, 36, 60, ..., 73, 52, 24]],

       [[47, 72, 76, ..., 88, 87, 91],
        [36, 95, 42, ..., 70,  8, 17],
        [72, 68, 33, ..., 86, 53, 14],
        ...,
        [ 0, 12, 95, ..., 74,  9, 25],
        [23,  0, 27, ..., 72, 98, 78],
        [ 0,  0, 74, ..., 58, 40, 60]],

       ...,

       [[44, 47, 79, ..., 21,  8,  6],
        [ 0,  0, 92, ..., 41, 30, 29],
        [ 0,  4, 55, ..., 64, 41, 18],
        ...,
        [ 0,  6, 56, ..., 90,  9, 36],
        [ 0, 71, 51, ..., 41, 42, 48],
        [ 0,  0, 15, ..., 12,  2

In [8]:
X.shape

(1000, 80, 400)

In [9]:
X=X.reshape(1000,400,80)

In [10]:
X

array([[[ 0,  0, 36, ..., 11, 20, 97],
        [78, 95, 10, ..., 24, 13, 70],
        [25, 22, 11, ..., 11, 73, 42],
        ...,
        [ 0, 48, 79, ..., 48, 95, 48],
        [52, 82, 94, ..., 58, 28, 32],
        [48, 52, 22, ..., 67, 50, 17]],

       [[ 0, 90, 15, ..., 90, 29,  4],
        [ 6, 21, 15, ..., 49,  9, 15],
        [76, 83, 20, ..., 29, 58, 73],
        ...,
        [19, 44, 50, ..., 36, 12, 94],
        [86, 14,  7, ..., 20, 29, 87],
        [35, 78, 48, ..., 73, 52, 24]],

       [[47, 72, 76, ..., 29, 68, 40],
        [72, 53, 67, ..., 36, 16, 14],
        [85, 82,  3, ..., 79, 12, 19],
        ...,
        [88, 46, 66, ..., 20, 76,  7],
        [65, 14, 19, ..., 37, 21,  3],
        [83, 77, 45, ..., 58, 40, 60]],

       ...,

       [[44, 47, 79, ..., 98, 93, 62],
        [93,  9, 58, ..., 87,  4,  6],
        [15, 15, 62, ..., 64, 53, 91],
        ...,
        [35, 36, 14, ..., 78, 64, 54],
        [50, 31,  7, ..., 59, 15, 31],
        [53, 45, 12, ..., 12,  2

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X, Y, test_size=0.3)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)
print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)

(700, 400, 80) (150, 400, 80) (150, 400, 80) (700, 1) (150, 1) (150, 1)


In [12]:
n_timesteps, n_features, n_outputs = X_train.shape[1], X_train.shape[2], Y_train.shape[1]

In [13]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

In [14]:
model=Sequential()
model.add(Conv1D(filters=32, kernel_size=3, activation='relu',input_shape=(400,80))) ##### LAYER 1 #####
model.add(Conv1D(filters=64, kernel_size=3, activation='relu')) ##### LAYER 2 #####
model.add(Conv1D(filters=128, kernel_size=3, activation='relu')) ##### LAYER 3 #####
model.add(Dropout(0.5))
model.add(MaxPooling1D(pool_size=3))
model.add(Flatten())
model.add(Dense(128, activation='relu')) ##### FULLY CONNECTED LAYER #####
model.add(Dense(n_outputs, activation='sigmoid')) ##### OUTPUT LAYER #####
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 398, 32)           7712      
                                                                 
 conv1d_1 (Conv1D)           (None, 396, 64)           6208      
                                                                 
 conv1d_2 (Conv1D)           (None, 394, 128)          24704     
                                                                 
 dropout (Dropout)           (None, 394, 128)          0         
                                                                 
 max_pooling1d (MaxPooling1D  (None, 131, 128)         0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 16768)             0         
                                                        

In [15]:
model.fit(X_train, Y_train, epochs=50, batch_size=1000, verbose=True)

Epoch 1/50
1/1 [==============================] - 5s 5s/step - loss: 10.8035 - accuracy: 0.4957
Epoch 2/50
1/1 [==============================] - 3s 3s/step - loss: 645.9843 - accuracy: 0.4786
Epoch 3/50
1/1 [==============================] - 3s 3s/step - loss: 253.2521 - accuracy: 0.4786
Epoch 4/50
1/1 [==============================] - 3s 3s/step - loss: 47.0414 - accuracy: 0.4786
Epoch 5/50
1/1 [==============================] - 4s 4s/step - loss: 3.0258 - accuracy: 0.5214
Epoch 6/50
1/1 [==============================] - 3s 3s/step - loss: 1.7050 - accuracy: 0.5214
Epoch 7/50
1/1 [==============================] - 3s 3s/step - loss: 1.0841 - accuracy: 0.5214
Epoch 8/50
1/1 [==============================] - 2s 2s/step - loss: 0.6983 - accuracy: 0.5214
Epoch 9/50
1/1 [==============================] - 3s 3s/step - loss: 0.6931 - accuracy: 0.5214
Epoch 10/50
1/1 [==============================] - 3s 3s/step - loss: 0.6931 - accuracy: 0.5214
Epoch 11/50
1/1 [==========================

In [16]:
_, accuracy = model.evaluate(X_train, Y_train, batch_size=1000, verbose=True) ### Training Accuracy ###

1/1 [==============================] - 1s 803ms/step - loss: 0.6931 - accuracy: 0.5214


In [17]:
_, accuracy = model.evaluate(X_test, Y_test, batch_size=1000, verbose=True) ### Test Accuracy ###

1/1 [==============================] - 0s 171ms/step - loss: 0.6931 - accuracy: 0.5200


In [18]:
y_pred=model.predict(X_test)
Y_test=Y_test.astype('int64')
y_pred=y_pred.astype('int64')

In [19]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.48      1.00      0.65        72
           1       0.00      0.00      0.00        78

    accuracy                           0.48       150
   macro avg       0.24      0.50      0.32       150
weighted avg       0.23      0.48      0.31       150



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred) 

In [21]:
cm

array([[72,  0],
       [78,  0]])